GuildToolsByFenInternals.lang = 'en'
GuildToolsByFenInternals.langStrings = {
    en =
    {
        member      = "Member for %s%i %s",
        deposits    = "Deposits",
        withdrawals = "Withdrawals",
        total       = "Total: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t (over %i %s)",
        last        = "Last: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t (%i %s ago)",
        minute      = "minute",
        hour        = "hour",
        day         = "day",
        last30Days  = "last 30 days: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        lastWeek    = "last week: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        thisWeek    = "this week: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        today       = "today: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        noRecords   = "no records found",
        bankGoldDeposits   = "BANK GOLD DEPOSITS",
        bankGoldWithdrawals   = "BANK GOLD WITHDRAWALS",
        inviteMessage   = "INVITE MESSAGE",
    },
    fr =
    {
        member      = "Membre pour %s%i %s",
        deposits    = "Dépôts",
        withdrawals = "Retraits",
        total       = "Total: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t (sur %i %s)",
        last        = "Dernier: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t (%i %s depuis)",
        minute      = "minute",
        hour        = "heure",
        day         = "jour",
        last30Days  = "last 30 days: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        lastWeek    = "last week: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        thisWeek    = "this week: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        today       = "today: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        noRecords   = "no records found",
        bankGoldDeposits   = "BANK GOLD DEPOSITS",
        bankGoldWithdrawals   = "BANK GOLD WITHDRAWALS",
        inviteMessage   = "INVITE MESSAGE",
    },
    de =
    {
        member      = "Mitglied seit %s%i %s",
        deposits    = "Einzahlungen",
        withdrawals = "Auszahlungen",
        total       = "Gesamt: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t (innerhalb von %i %s)",
        last        = "Zuletzt: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t (vor %i %s)",
        minute      = "Minute",
        hour        = "Stunde",
        day         = "Tag",
        last30Days  = "last 30 days: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        lastWeek    = "last week: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        thisWeek    = "this week: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        today       = "today: %i |t16:16:EsoUI/Art/currency/currency_gold.dds|t",
        noRecords   = "no records found",
        bankGoldDeposits   = "BANK GOLD DEPOSITS",
        bankGoldWithdrawals   = "BANK GOLD WITHDRAWALS",
        inviteMessage   = "INVITE MESSAGE",
    }
}